from datetime import datetime, date
from config import db
from marshmallow_sqlalchemy import SQLAlchemyAutoSchema


class MarinaLitterWatch(db.Model):
    __tablename__ = "mlw"
    mlw_id = db.Column(db.Integer, primary_key=True)
    communityname = db.Column(db.String(128))
    beachname = db.Column(db.String(128))
    beachcountrycode = db.Column(db.String(2))
    beachlength = db.Column(db.Integer())
    beachlocation = db.Column(db.String(32))
    beachtype = db.Column(db.String(32))
    eventdate = db.Column(db.Date())
    eventtype = db.Column(db.String(32))
    natref = db.Column(db.String(8))
    lon_x1 = db.Column(db.String(16))
    lat_y1 = db.Column(db.String(16))
    lon_x2 = db.Column(db.String(16))
    lat_y2 = db.Column(db.String(16))
    g1 = db.Column(db.Integer())
    g3 = db.Column(db.Integer())
    g4 = db.Column(db.Integer())
    g5 = db.Column(db.Integer())
    g7 = db.Column(db.Integer())
    g8 = db.Column(db.Integer())
    g9 = db.Column(db.Integer())
    g10 = db.Column(db.Integer())
    g11 = db.Column(db.Integer())
    g12 = db.Column(db.Integer())
    g13 = db.Column(db.Integer())
    g14 = db.Column(db.Integer())
    g15 = db.Column(db.Integer())
    g16 = db.Column(db.Integer())
    g17 = db.Column(db.Integer())
    g18 = db.Column(db.Integer())
    g19 = db.Column(db.Integer())
    g21 = db.Column(db.Integer())
    g22 = db.Column(db.Integer())
    g23 = db.Column(db.Integer())
    g24 = db.Column(db.Integer())
    g25 = db.Column(db.Integer())
    g26 = db.Column(db.Integer())
    g27 = db.Column(db.Integer())
    g28 = db.Column(db.Integer())
    g29 = db.Column(db.Integer())
    g30 = db.Column(db.Integer())
    g31 = db.Column(db.Integer())
    g32 = db.Column(db.Integer())
    g33 = db.Column(db.Integer())
    g34 = db.Column(db.Integer())
    g35 = db.Column(db.Integer())
    g36 = db.Column(db.Integer())
    g37 = db.Column(db.Integer())
    g40 = db.Column(db.Integer())
    g41 = db.Column(db.Integer())
    g42 = db.Column(db.Integer())
    g43 = db.Column(db.Integer())
    g44 = db.Column(db.Integer())
    g45 = db.Column(db.Integer())
    g46 = db.Column(db.Integer())
    g47 = db.Column(db.Integer())
    g49 = db.Column(db.Integer())
    g50 = db.Column(db.Integer())
    g52 = db.Column(db.Integer())
    g53 = db.Column(db.Integer())
    g54 = db.Column(db.Integer())
    g56 = db.Column(db.Integer())
    g57 = db.Column(db.Integer())
    g58 = db.Column(db.Integer())
    g59 = db.Column(db.Integer())
    g60 = db.Column(db.Integer())
    g62 = db.Column(db.Integer())
    g63 = db.Column(db.Integer())
    g64 = db.Column(db.Integer())
    g65 = db.Column(db.Integer())
    g66 = db.Column(db.Integer())
    g67 = db.Column(db.Integer())
    g68 = db.Column(db.Integer())
    g69 = db.Column(db.Integer())
    timestamp = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class MarinaLitterWatchSchema(SQLAlchemyAutoSchema):
    class Meta:
        model = MarinaLitterWatch
        include_fk = True
        include_relationships = True
        load_instance = True
