swagger: "2.0"
info:
  description: >
    This data set is a subset of Marine Litter Watch’s data. It was compiled to
    help answer the Earth Challenge 2020 research question, “What is the Extent
    of Plastic Pollution?”
  version: "1.0.0"
  title: Marine Litter Watch (MLW) Plastic Pollution
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /:
    get:
      operationId: ui.home
      tags:
        - UI
      summary: Get Swagger UI Home
      description: Get Swagger UI Home
      responses:
        200:
          description: Successfully got Swagger Home

  /mlw:
    get:
      operationId: mlw.read_all
      tags:
        - MLW
      summary: Read the entire set of servers, sorted by hostname
      description: Read the entire set of servers, sorted by hostname
      responses:
        200:
          description: Successfully read mlw set operation
          schema:
            type: array
            items:
              properties:
                index:
                  type: string
                  description: Id of the mlw
                beachname:
                  type: string
                  description: Beach Name
                communityname:
                  type: string
                  description: Community Name


    post:
      operationId: mlw.create
      tags:
        - MLW
      summary: Create a mlw
      description: Create a new mlw
      parameters:
        - name: mlw
          in: body
          description: MLW to create
          required: True
          schema:
            type: object
            properties:
              beachname:
                type: string
                description: Beach Name
              communityname:
                type: string
                description: Community Name
      responses:
        201:
          description: Successfully created mlw
          schema:
            properties:
              index:
                type: string
                description: Id of the mlw
              beachname:
                type: string
                description: Beach Name
              communityname:
                type: string
                description: Community Name


  /mlw/{index}:
    get:
      operationId: mlw.read_one
      tags:
        - MLW
      summary: Read one MLW item
      description: Read one MLW item
      parameters:
        - name: index
          in: path
          description: Id of the mlw to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read item from mlw data operation
          schema:
            type: object
            properties:
              index:
                type: string
                description: Id of the mlw
              beachname:
                type: string
                description: Beach Name
              communityname:
                type: string
                description: Community Name


    put:
      operationId: mlw.update
      tags:
        - MLW
      summary: Update a mlw
      description: Update a mlw
      parameters:
        - name: index
          in: path
          description: Id the mlw to update
          type: integer
          required: True
        - name: mlw
          in: body
          schema:
            type: object
            properties:
              beachname:
                type: string
                description: Beach Name
              communityname:
                type: string
                description: Community Name
      responses:
        200:
          description: Successfully updated mlw
          schema:
            properties:
              index:
                type: string
                description: Id of the mlw in the database
              beachname:
                type: string
                description: Beach Name
              communityname:
                type: string
                description: Community Name

    delete:
      operationId: mlw.delete
      tags:
        - MLW
      summary: Delete a item from the mlw list
      description: Delete a mlw
      parameters:
        - name: index
          in: path
          type: integer
          description: Id of the mlw to delete
          required: true
      responses:
        200:
          description: Successfully deleted a mlw
