swagger: "2.0"
info:
  description: >
    Subset of Marine Litter Watch’s data to help answer the Earth Challenge 2020
    research question, “What is the Extent of Plastic Pollution?
  version: "1.0.0"
  title: Marine Litter Watch (MLW) Plastic Pollution
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /:
    get:
      operationId: ui.home
      tags:
        - UI
      summary: Get Swagger UI Home
      description: Get Swagger UI Home
      responses:
        200:
          description: Successfully got Swagger Home

  /mlw:
    get:
      operationId: mlw.read_all
      tags:
        - MLW
      summary: Read the entire data set, sorted by id
      description: Read the entire data set, sorted by id
      responses:
        200:
          description: Successfully read mlw set operation
          schema:
            type: array
            items:
              properties:
                mlw_id:
                  type: string
                  description: Id of the mlw
                appid:
                  type: string
                  description: Register ID
                hname:
                  type: string
                  description: hostname of the server
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the mlw

    put:
      operationId: mlw.update
      tags:
        - MLW
      summary: Update a mlw
      description: Update a mlw
      parameters:
        - name: mlw_id
          in: path
          description: Id the mlw to update
          type: integer
          required: True
        - name: mlw
          in: body
          schema:
            type: object
            properties:
              appid:
                type: string
                description: Application ID
              hname:
                type: string
                description: Hostname of the mlw
      responses:
        200:
          description: Successfully updated mlw
          schema:
            properties:
              mlw_ud:
                type: string
                description: Id of the mlw in the database
              appid:
                type: string
                description: Application ID
              hname:
                type: string
                description: Hostname of the mlw
              timestamp:
                type: string
                description: Creation/Update timestamp of the mlw record
