swagger: "2.0"
info:
  description: >
    This data set is a subset of Marine Litter Watch’s data. It was compiled to
    help answer the Earth Challenge 2020 research question, “What is the Extent
    of Plastic Pollution?”
  version: "1.0.0"
  title: Marine Litter Watch (MLW) Plastic Pollution
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /:
    get:
      operationId: ui.home
      tags:
        - UI
      summary: Get Swagger UI Home
      description: Get Swagger UI Home
      responses:
        200:
          description: Successfully got Swagger Home

  /mlw:
    get:
      operationId: mlw.read_all
      tags:
        - MLW
      summary: Read the entire set of items, sorted by communityname
      description: Read the entire set of items, sorted by communityname
      responses:
        200:
          description: Successfully read mlw set operation
          schema:
            type: array
            items:
              properties:
                index:
                  type: integer
                  description: Id of the mlw
                communityname:
                  type: string
                  description: Community Name
                beachname:
                  type: string
                  description: Beach Name
                beachcountrycode:
                  type: string
                  description: Beach Country Code
                beachregionalsea:
                  type: string
                  description: Beach Regional Sea
                beachlength_m:
                  type: string
                  description: Beach Length in meters
                beachlocation:
                  type: string
                  description: Beach Location
                beachtype:
                  type: string
                  description: Beach Type
                eventdate:
                  type: integer
                  description: Date of the event
                eventtype:
                  type: string
                  description: Event Type
                natref:
                  type: string
                  description: NAT Reference
                lon_x1:
                  type: string
                  description: Longitude X1
                lat_y1:
                  type: string
                  description: Latitude Y1
                lon_x2:
                  type: string
                  description: Longitude X2
                lat_y2:
                  type: string
                  description: Latitude Y2
                gs:
                  type: integer
                  description: Type of plastic

  /mlw/{index}:
    get:
      operationId: mlw.read_one
      tags:
        - MLW
      summary: Read one MLW item
      description: Read one MLW item
      parameters:
        - name: index
          in: path
          description: Id of the mlw to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read item from mlw data operation
          schema:
            type: object
            properties:
              index:
                type: integer
                description: Id of the mlw
              communityname:
                type: string
                description: Community Name
              beachname:
                type: string
                description: Beach Name
              beachcountrycode:
                type: string
                description: Beach Country Code
              beachregionalsea:
                type: string
                description: Beach Regional Sea
              beachlength_m:
                type: string
                description: Beach Length in meters
              beachlocation:
                type: string
                description: Beach Location
              beachtype:
                type: string
                description: Beach Type
              eventdate:
                type: integer
                description: Date of the event
              eventtype:
                type: string
                description: Event Type
              natref:
                type: string
                description: NAT Reference
              lon_x1:
                type: string
                description: Longitude X1
              lat_y1:
                type: string
                description: Latitude Y1
              lon_x2:
                type: string
                description: Longitude X2
              lat_y2:
                type: string
                description: Latitude Y2
              gs:
                type: integer
                description: Type of plastic
