swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /:
    get:
      operationId: ui.home
      tags:
        - UI
      summary: Get Swagger UI Home
      description: Get Swagger UI Home
      responses:
        200:
          description: Successfully got Swagger Home

  /mlw:
    get:
      operationId: mlw.read_all
      tags:
        - MLW
      summary: Read the entire set of servers, sorted by hostname
      description: Read the entire set of servers, sorted by hostname
      responses:
        200:
          description: Successfully read mlw set operation
          schema:
            type: array
            items:
              properties:
                mlw_id:
                  type: string
                  description: Id of the mlw
                appid:
                  type: string
                  description: Application ID
                hname:
                  type: string
                  description: hostname of the server
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the mlw

    post:
      operationId: mlw.create
      tags:
        - MLW
      summary: Create a mlw
      description: Create a new mlw
      parameters:
        - name: mlw
          in: body
          description: MLW to create
          required: True
          schema:
            type: object
            properties:
              appid:
                type: string
                description: Application ID of mlw to create
              hname:
                type: string
                description: Hostname of mlw to create
      responses:
        201:
          description: Successfully created mlw
          schema:
            properties:
              mlw_id:
                type: string
                description: Id of the mlw
              appid:
                type: string
                description: Name of the application
              hname:
                type: string
                description: Hostname of the mlw
              timestamp:
                type: string
                description: Creation/Update timestamp of the mlw record

  /mlw/{mlw_id}:
    get:
      operationId: mlw.read_one
      tags:
        - MLW
      summary: Read one MLW item
      description: Read one MLW item
      parameters:
        - name: mlw_id
          in: path
          description: Id of the mlw to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read item from mlw data operation
          schema:
            type: object
            properties:
              mlw_id:
                type: string
                description: Id of the mlw
              appid:
                type: string
                description: Application ID
              hname:
                type: string
                description: Hostname of the mlw
              timestamp:
                type: string
                description: Creation/Update timestamp of the mlw record

    put:
      operationId: mlw.update
      tags:
        - MLW
      summary: Update a mlw
      description: Update a mlw
      parameters:
        - name: mlw_id
          in: path
          description: Id the mlw to update
          type: integer
          required: True
        - name: mlw
          in: body
          schema:
            type: object
            properties:
              appid:
                type: string
                description: Application ID
              hname:
                type: string
                description: Hostname of the mlw
      responses:
        200:
          description: Successfully updated mlw
          schema:
            properties:
              mlw_ud:
                type: string
                description: Id of the mlw in the database
              appid:
                type: string
                description: Application ID
              hname:
                type: string
                description: Hostname of the mlw
              timestamp:
                type: string
                description: Creation/Update timestamp of the mlw record

    delete:
      operationId: mlw.delete
      tags:
        - MLW
      summary: Delete a item from the mlw list
      description: Delete a mlw
      parameters:
        - name: mlw_id
          in: path
          type: integer
          description: Id of the mlw to delete
          required: true
      responses:
        200:
          description: Successfully deleted a mlw
